apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-system
# This kustomization need to run with --server-side parameter (else use replace --force)

resources:
  - https://github.com/actions/actions-runner-controller/releases/download/v0.22.0/actions-runner-controller.yaml
  - runnerdeployment.yaml

generators:
  - secret-generator.yaml