apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - namespace.yaml

helmCharts:
- name: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns/
  releaseName: external-dns
  namespace: external-dns
  version: 1.15.0
  valuesFile: values.yaml

generators:
  - secret-generator.yaml