apiVersion: v1
data:
    apiKey: ENC[AES256_GCM,data:DAw8/qUh65oPFx5Ti7Soh3P4rNP4HZnVNkmLnhS9gf2nzJ/Dp93ahC1pH/Msb5kc+MXKosI7Ssc=,iv:SwrL5ko0htuHcxtO89nFSPE10RCp01RUlyHq7q9NN3A=,tag:RkuXK9uegnhnTvrmpITK0A==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNEg5QXF6ZkhqSXZYdzRV
            T0VKVGtaOG11L1FRUmt0M0twbVJSVmVYMFdFCnlnRXdKNFhCZjA2VlBzS0pjaE5P
            YUJRS0o3YVNsTXkrN1dEcWYzdFpJNXcKLS0tIEdIYk5NckRUbFM0UEJzdmEvL2dS
            cDZpU2tmdVdNUmxqWGErVlNkTlpKMzAKVrdbP3CJQ43hJVo0CapDqJHzEUYq2Zls
            b1jBdERKZsgLcfgXCB0Zdpz0dwp7IzmWJ4+0v8NhWtVb8F3+rq/qYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R1JkMGxLSHEydjJDL3N3
            WXFtOGJSZHpjbHFqWk4vc2NrYzNuMlFBVFM0CjUwbm01bHA0ekhwZWdRMFRvZ3Bj
            QjMzNmt4MVJOTkxoNFdqcFpGeWFObXMKLS0tIEg5WjNVZFkxVTNSQXFDTGRZMjBC
            MmZrM04yanVuaWx2cHlTbmhsQ2VmdHcKs43UkBLXFKVRo8Q8KOW4vlsQlfRPLb+p
            k7sJgbAeG7JEOJHNfC4/RprJQxtPtVDoNTbegyTV+GIOFak/BDTvWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T21:54:15Z"
    mac: ENC[AES256_GCM,data:P0H3NHBJfMfJ5HcSNI4WOStZ5WYYeU/X6mqAymDVdnwP2BcxE+dRlj1Q0ZhuhZPZuWn89C1Z2s/nfmVBQqonLXOULD57rL9MheOsN2KwLAXrJInWhvfh35wAYcKw6nmyk4kTzfsHa1YdBYpoOjl/1SKiIDXWXqafTRdIjUkfsHY=,iv:icuIiFNf54GVDB3HFRB9ZaSph28CRXEaB0r2ItHrUu8=,tag:sFUXfYcYQJRoHQ96mg+M1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    version: 3.9.0
