apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.25/releases/cnpg-1.25.0.yaml
