apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/ha/install.yaml
- httproute.yaml
- appset-cilium.yaml
- appset-core.yaml
- appset-apps.yaml
# - secret-github.yaml # this is required to allow access to your repo even if it's public

configMapGenerator:
- name: argocd-cm
  literals:
  - kustomize.buildOptions=--enable-alpha-plugins --enable-exec
  behavior: merge
- name: argocd-cmd-params-cm
  literals:
  - server.insecure=true
  behavior: merge

patches:
- path: ksops.yaml

# generators: # works only when ArgoCD is deployed
#   - secret-generator.yaml