apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-menia-cc-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:k0BUKBtdNx/72DuqwBkW0DQLblO8vCQ/47is5AaTR7jIPR2157iGUw==,iv:eyWQSQQ2SnNWwkFlWyvXk2OeBc/ZbzjrCSUqtgbLooo=,tag:MjUv58IExXFU4H9V1aMdeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bElaeXNSVlBNMVVYQXhw
            dnJhRmF4V01Yc3EvMUUyUkVwWGI2U3dnMEJjCllISThPdnUwbk1DSUl5UklTclRN
            aDM4YXFPTTdweFk0WW1NajVzVVRKZGcKLS0tIFgvVFJZMDcyUXp2VUJRTit6Si9U
            R2tJNFdaMGg2MW1jZUlVbDJWdExVbGMK03rCU0pnx3gBveEDv18fO8SqVxRidxGn
            lT0x0Kr72mbiWsSqd5aR2+vqBMenltfVJDItcVmUgu96ONEJ258Izg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVFVjTWVCQVdFTWtZbloy
            cTlDQW41c1RmY1FuaXZGYnhwcDRTbDlaQUdVCkF4Z2hENGs0U080bDlKMEFPaHE5
            OWlGdzRtT2hLM3ZBNjh4a0NrTlZGb3cKLS0tIFVzRGREU01wVWwyL0MvRWpMSDU0
            RE9DWnpFaDlCcGVWMWVjR0tZZjlMeW8K2BdagcP41hPf2E5kiQQYWf+IpRWwS01b
            KDmUCfCyNiAGAo2dMxhR49V6j5G6fm4g5YP7mzQmWeCfG9XdBICjQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T23:56:20Z"
    mac: ENC[AES256_GCM,data:TmYENi0NY4HTPBK6iNbBtbFQ0RQctMiXrMgmH2J2fYK7rs0NSysbsizqwHPPSK0Y7NDqZsUSvmE5eayurgfUbAs9/TmwTkNg4omyfoYS3yfXocxMCfjHpiQVRbr9ZXyTnuYUhBrFE9JpyBQYIK9FnV71kYTukHcGnKIOeBKu8tc=,iv:dzzZThgO24MUiBtxIyKzqxtBC7gCpO/0Zz0um7ufyyg=,tag:CxnoKu6Nh+DQaQbBaEqc4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
