apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:v3.4.3
        ports:
        - containerPort: 8191
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: "none"
        - name: PROMETHEUS_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
  - port: 8191
    targetPort: 8191