apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm

resources:
  - litellm.yaml
  - httproute.yaml

configMapGenerator:
  - name: litellm-config
    files:
      - config.yaml

# generators:
#   - secret-generator.yaml
