apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: litellm-secrets
data:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:A93N92pRDXycUyY/y923NPrCap0TRC3xd84Gi4km1zhkpMe92QEqr+Z6RUmZ4L9cCC44ElyBq8YxbzQXMD5CA2gs8J21BzgaRai6HTP4fCx5kccEXvlyPYCewXr8vQ4AOaXXmw==,iv:2cXTVey13JqWktEEatrzJgaltMDLTyQ7ZwrScPCsNcI=,tag:7DYgflQ9l9lAecXsWQusIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1o4M0NzUzNuUVk4OVJK
            K201RkJnMnB3dEJBTDc0VDlrWWI2cVVjNUVBCnoydEs1Nnp3cWd4U2p3RndldTJu
            YkhXT1BHTm9tUWFERHArVnQ0aW5nU1kKLS0tIDRKMGI0eHlpR0dYTUtJMktUMzVh
            RWZuRkRsQ0ZFQzlHUEZ4NzhZaTE1QUEKqG6msDhvSyDhi2+/hkjbgjC16MXR7Ofa
            UIsqoGNM8wDtKNvmggY2slY7rJ9iubt9vVcuWhj23G9oYnQ4T0OwpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ0IxNUQrWjB1Z1NsNVBT
            czBwdmQ5R29hVVhzWUV6elhQRGxvNjVFTXhBCnFjSExQVlB4b01waXVicWdzdGJP
            eHlkL0lrVStuTW9raUpOdUxLZDBRd0UKLS0tICtHdHk2YUFFekppclFOaThNTlFl
            RWErRUMvcDI3QTNkbW9mY2RyWWRmUE0K0L1qZBXE249dQWEVnLK+w6Fg3mK0g9IS
            cDW+lYTIAeVdtKHxZrsBgmeo5uuyMV3hH203YexxktM2MbA/VLJ4TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-06-19T23:52:37Z"
    mac: ENC[AES256_GCM,data:X6HwHdE+kVGEUITBrVt7nYNIijRl4oWr5QdOXhH2Hq9jWgLSWWR8M8uFM3uTPeM9oJz+0RSbivwDZEotTzIjTFWl5sRyRTU2fzy1Ehlkjj39F6wAsaCZywh5W/Mg3YYiho3AfIxxdQeeGXRnAsZQbfcYAFflKIIy01cO3vFxqD0=,iv:SQMif+ib0zC0rBQLOXK0bfL9byrjC9rcSmVRcIiE66k=,tag:fWUp0pp4EtgC3lS5Yos8NA==,type:str]
    version: 3.13.1
