apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tunnel-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secret-tailscale.enc.yaml
  - secret-playit.enc.yaml
