apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tailscale-operator
  repo: https://pkgs.tailscale.com/helmcharts
  releaseName: tailscale-operator
  namespace: tailscale
  version: 1.70.0

generators:
  - secret-generator.yaml