apiVersion: v1
kind: Secret
metadata:
    name: talos-backup-storage
    namespace: talos-backup
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N+aEXt5MBncUR4VvwuyWajSjrY7EsR1elw==,iv:n3fNxTw1AfO/NJBU/ho1yg2rm3Q83venXJzt5EkzTyY=,tag:LjXNWzASdQ2xIdQwvP1vUQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7V2AmaW+cTyyPc6Kaze8vQNi/kVZKWPLYHixo3X6tQ==,iv:EidNaFmrE7TQmZXSZTKLVUwd3zyh1iNOwrI/ikG6T64=,tag:BCO9XbY7+GWdvQmdWPkyVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbUdOREwvdmJaSEIwSks4
            MXYrOXl6YURWby9yWnFuOE5HUmQ0emV6ZDNZClhIQ3FveGU2RUxKbDNZR0tabkkv
            c0tqdWRhTThIK0RPVDFKa2FVTEFDVGsKLS0tIFprSHFlaUdNUmUrdE40YktZZkN0
            bDNuSGZKc2xqditvZXkxOXpxek9nejQKDZF7o7SAZyauuhK+SNPILabCobsDonpt
            kanN+wlSLL4ZKfs3M2n4Vq2rZjcBdAbzqFpB6IQNSFtk29LPTfGFfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSndiWWNWY2VtU3ExTUw3
            SWg0dzNVem5HN2hLTGx4M1J3SDFGcFUxeVFFCmVYQ1NXTitDWmZtWVJmazF5cTcw
            MjNpSC9zWDBIbDFIMTNzaDA5QSt1d1UKLS0tIFRVck5OQSt1VjVxU09Mb0Z3dVFk
            SVR5eURGOXRwd1E1c1hmY1NML2FXMFEKJwjmw2Hfjlq4BQ7/+ooZ4YhOMwjBZq4/
            JJ1gvs2sg8LCU+2uCBzYN/QQQQLdfCpmO/5N3GezsYZKjGUxnaW8eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-06-23T12:39:55Z"
    mac: ENC[AES256_GCM,data:I5A8uQllBssBhqU/FE3wWePOZyw9JewBMxT4/Gs63AiJn5p6dbG8zRs+RfhKq6xX1vqqZcJBcdFlnJNxKD/nIAZeyfIUaWzn7eyBtj13fHo3isb59Hk/7IuGq3LLCnRHfOVETKx6hB7e1NUlHRPZ16+NOBXPU2Ue1lVuyUYXkM8=,iv:vr4qcfiPGkqfU0ydBx65GdtgpxM5kEWKfxBooM43r6M=,tag:Xd+p31EsQSGtRPyAbxlUdw==,type:str]
    version: 3.13.1
