apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-operator
  namespace: clickhouse-operator
spec:
  template:
    spec:
      containers:
      - name: clickhouse-operator
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"