apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rybbit

resources:
  - namespace.yaml
  - clickhouse-bootstrap.yaml
  - clickhouse.yaml
  - secret.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - httproute.yaml
  - rybbit.yaml

labels:
  - pairs:
      app.kubernetes.io/name: rybbit
      app.kubernetes.io/instance: rybbit
