apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources: # https://www.talos.dev/v1.9/kubernetes-guides/configuration/deploy-metrics-server/#install-after-bootstrap
- https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml
