apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-components
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/o-be-one/kubernetes-at-home.git
      revision: HEAD
      directories:
      - path: 'core-components/**'
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: "menia"
      source:
        repoURL: https://github.com/o-be-one/kubernetes-at-home.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true