apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
- httproutes.yaml
- applicationset.yaml

configMapGenerator:
- name: argocd-cm
  literals:
  - kustomize.buildOptions=--enable-alpha-plugins --enable-exec
  behavior: merge

patches:
- path: ksops.yaml