apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
type: Opaque
# key and token in Beszel hub ui
stringData:
    KEY: ENC[AES256_GCM,data:w051/Ohxik3TDyxMZPgxFCL9Col0AP1N6CZhxjFSd+sKobLA3p2eWvwq7R9bX402/blpa6plYIvAOWQsMzhU5sfj5/S/sXuclfQEJ6/U4Zg=,iv:Ss8ye2h3b6epVt7mTsfiYm0Ech+Cb6b0zcumyt7Fa0I=,tag:hdLLDVjX8SP/cFeN+mP2KQ==,type:str]
    TOKEN: ENC[AES256_GCM,data:66ReY5uFHp4+sCgAQlXApS7be14GTfPxghqrSAvLpPIo1fNp,iv:dqXKPjTWvuJ3GoQGoeuDg9/rar4D7QYf2EraPn2YesY=,tag:HX7NDt1jaIxChcBQz8HQbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMFdhcHdDVzdHeHFKODQx
            cjdiM0JqdmtTU1MrTFVkSll3V01qQUtOdng4CjJMV0xzblJ0TFdNdFZwVGV0QmRq
            a09MUjB6azlIMkNWdnV6MjN6OTN0amMKLS0tIFp4V2M4eUdSWEJUUVBkSzBmWEFM
            c0xvZTlQWlVvRWJEQjBpeUVzZWxpTTgKFwJsCn+khxGRuy555LkRgasGDdjMWwJe
            eBUCcTRqDXgdRsvydOEFYeoGw6/+ulwZZ6ifzGXEMBbfmWCiiL1sPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZTB1MVJVb28yckVzQnkx
            VVpNOGh1RXlaUjM1TG5CR2pHakJjbk8yalJBCnQxckFTc2NpNGQrS0NyTmd0cGc0
            ZTBRZnoxMnozbmhhSEpBck45T0lxQmsKLS0tIE9BRkp1d1NkVmlTSnh5TnBJNEZL
            SUFXSU9NK2Q0RzVaSERaNjV6Z3RORjQK6SfYvOdzdyDYs9wBuVRQ7CbfaAYBJXEm
            7wqTLnOHsnqfG4irUEC7l6aYiXKkmrICdAScCRB0cdD6FNHk+X8YBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-07-10T23:27:38Z"
    mac: ENC[AES256_GCM,data:4SMmYPLL6hX3coPRLo3qv5vkh6QnsNAc1CF8sIunF8+jNDweIn8fU7ci21xwOizFhNT/wU8IDtdsm0XSVbua7/20VzbK67MzEX3jJjfPS2D0xb/btyjfm8f/lu2+qPUT06HMca2HS91ossCkBfZDecbIiUQ1ZEfpqwtS4T4/zC0=,iv:xDiBtU13WNfv1A1JzuVFD05pMkCHMbpRLJRTF2m6E9Q=,tag:9QghpGkb7i3L3oOE5PDgJQ==,type:str]
    version: 3.13.1
