apiVersion: v1
kind: Secret
metadata:
    name: backup-storage
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GeM8N0HkMjU9O+mV/Lv6Eij/YMuSJyy3J/Ed/O6jO97xlD6y,iv:7b1fhcbd4XrjKfBLbzp4QxBV6/ApVkiHJNNBVUkqpZ0=,tag:XMndG5NJzBUei60Mo0+kZA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R5sMZyqbx73nxr9QRNZFe9qOVT/d6S5BkmKS3epiiH0dnlY5+OlyTQ+V1AA=,iv:/CgZjIoxOWkQN7nle6F5mPujh/HqtNYe6qxQza9r5t0=,tag:9bhEnvZIhRdLf9+cubsHqA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:mPmK8e+vZkjK2+OSkU1l0RwtgWF1a25FEns5OE24KWXYAJPbPEBm7LaeQjEjkzPJnuY8ww==,iv:Dhhs3WGSyvsK937jnYPP9uh0wKZCNl/KwFWLUWw3aYw=,tag:7Pr/EVnuruTBXU+U2kQbsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK0d3RlNUQnRja1EydWZF
            bjhMclRYbFBESnpCdDFiWlIzN2pJZm5oNUdVCkF3aGhXV3pjdjl4OGR5YnNrdTVY
            eEJ5QXRvUWFwdUc4UGZveDR2eW1LQkEKLS0tIDdzT2VaRkg1U0RuVmxqT1Y5ZUd0
            eUhjTGtzaTNLbVlENDNBWGhJRE8vVlkKn/zh1RinAWpuLz07Kkfbht1CR95IrNRC
            OZjGFurhKslysd+l+aNDfy2+/ikq0+LZWpkn5tQjGcEfaoGubA7xNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdDZxaXg5OUZ3TlliMWdS
            ZEJvd2ptV0xtbEhlWDJiVEg4NFZXcmJtMUhRCkMzdnlXR2xMcUg2dWhiclh0RXRG
            UTRkRzVyYXZvU0xOWjhhMktQd1MzeEUKLS0tIHJ0cFZ6OFRHQXROTVJBa2dQRjlE
            T2x4TzRIL0M4eHN3WjY1U1lOY1llSmsKpwMl5sRvmGMAeIdHwNJr4pphaMZ6h8Jq
            TeotfC83MYLoQD3ZkEr1IP9aXWKvFKq9VRUU3lG29smAsAlUUAR0YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T02:06:50Z"
    mac: ENC[AES256_GCM,data:erKMc1Y7BOosIDJN4CTBlX0uGSHf0Q6SrYn2WTzHfAWRuOu7VuTBP6BaaJetTo5Mhm3sr/zQ/u8v5WvTimiCaw7luXaXw7f7pX9MnsbmtljEleEMinr3MKnxRJZxo1+5uj56lObLPy6WWEw2OkTS1e8n+U/0kuuWfFvxgUnfha0=,iv:kgQUwPMg5u62LWbjx1nt0A/s68BvkDBtkyc0zFc4N5Y=,tag:PHnzYR9OqfhU4Gage9vayA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    version: 3.9.0
