apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.7.0/deploy/longhorn.yaml

patches:
  - path: namespace.yaml

generators:
  - secret-generator.yaml