apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.7.0/deploy/longhorn.yaml
  - httproutes.yaml

patches:
  - path: namespace.yaml

configMapGenerator:
  - name: longhorn-storageclass
    files:
      - storageclass.yaml
    behavior: replace
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/instance: longhorn-system
        app.kubernetes.io/version: v1.7.0

generators:
  - secret-generator.yaml