apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.7.0/deploy/longhorn.yaml
  - httproutes.yaml
  
patches:
  - path: namespace.yaml
  - path: storageclass-patch.yaml

generators:
  - secret-generator.yaml