apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.7.1/deploy/longhorn.yaml
  - httproute.yaml

patches:
  - path: namespace.yaml

configMapGenerator:
  - name: longhorn-storageclass
    behavior: merge
    namespace: longhorn-system
    files:
      - storageclass.yaml

generators:
  - secret-generator.yaml