kind: Secret
apiVersion: v1
metadata:
    name: opendesign-secret
type: Opaque
stringData:
    OD_API_TOKEN: ENC[AES256_GCM,data:9UVhygb68kC5Lrp4lb9okSKRgbeh2gt7dthxpU0inYvI0IAw29MLVeYhVnHCUxnkjq8=,iv:S9KGUkEA53x1xCujDpRVO5psNoWAtjTtA+Hcau9RUZc=,tag:ZwPwnsGFvhLw16rBlcn9xQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcDM3L1NIb2swRDRnQlJ2
            YkVQTEdDSWMxUklxYUdQUXQ4NjVCLzZjUFdnCnFiL040M25peHErN1pFMFl1Zkdp
            U1JDekpIdzNRYm43d3pkOHcyUDduelEKLS0tIEpQcHpESVZZcHJkVmJ6NUxMUjdh
            SFlNK1NEUDdFSVJWZk4wSWRVSWtSOU0KhyUSl6wEgPwy/LnYZ1Y1DwN42nqWqs1a
            Px8fcXEQDao2k+dD7MfJBYc14d0VfNnyZEADai9VemLjhcfV8wM74g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYmwwVHh2Uk1QM1M1bzhx
            b3M2Qlk5ekZYUEdEeWF3aE93UFRVS2hsUkFZCnlpNHZqRzNBOXJXakMwMDkwZ2JR
            L0R2M0F5Rlh2bTIrSTVuOGcxd1JiMHcKLS0tIFUvUXR1ajdpU2RFTi9pL0ZjS2s3
            RVFHc3NIUFlDdEY2Tm5jMzNLczBtZlUK079kixJ4ebOLli2IFLcNbP0KutKTK4IA
            370iO1qoyfKyzilnQ6BglGlAy7xT9I7KVoNXD8XYZvpeB0B1LciV1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-06-14T18:44:04Z"
    mac: ENC[AES256_GCM,data:dPwiHsokW/On7Kr63kp9vA06mbhmYo5gVxrvxTKz1k7ZoNFDIXd1EkyS8qK3pvl4NJrIRUOgmnoP2IQk6wvFON+cXwGN0CsVB8zslj9bey1Gpabw8co4w/PQP1fi1QGtvI0s0zhL/R2EHRwSTJKvQiL/mSTqzAPsV0hiKFfaog8=,iv:/J9HpTzyLecBm5Fvzki9dhhi9w/+lVAaLkFJmq0fwwE=,tag:inzJcTX8dgjJ8twMBlg3sw==,type:str]
    version: 3.13.1
