apiVersion: v1
data:
    github_token: ENC[AES256_GCM,data:7Q4XN7TlrL3+y82aOwgrdEI1oCZ33zNn/z4En0WycbT2GZJ/nO1fwJURitaGv5hG0sk/H2DmBCI=,iv:0/BvzKKwIyNvcvGcwcjvdTJb1qM5prx/30c0wpTXku4=,tag:Y06Vk351RwursY6ZmyR+AA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: controller-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUkpXeE9rV2J2RGpNdSt3
            Ymh2NEpIYWpFUExad0plSnhMV3lPZWRxejFnCk5QU0o3bDFreFU4T0lSelJxbFY4
            dUhUSWttdEM0VS83bjNWMmNydGhwRFkKLS0tIGQ0OGQrdHdUb3RVVURDK3hXNjhv
            NDNTWC9NTGJvWUR5WEhSOTZ6eGVYSFUKMsF1//WftdTKnl/PQU2/52SuVXHv+zOP
            cNaMtmyo1i/mBsdJsYDXBJdlT3+CYqnUAsaJZ5ZamP9sh2zKxYmBvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUE5CNDNBRTg3ZmpnaTZY
            SnhMNnZqZHEvUVRpcnQvQnRkNXJUWjEzRlRzCnBzbzhMVmgvempYV0RrTVdnNzd2
            WFpFdnlOZ0RmN3pPYzJiQ3FTTGJ6cVkKLS0tIC9NVGJZVkVWN1BCYUVvNmFnZ0Zk
            dnpWUkJmdzEwNlkrZm44SWxNbUdNVVUK/+ZJzCHod63nErYeoUSHLQijTb0R/mJZ
            BAtcfqGObjXmovjffmixhRtd+PhaAu4I1+ncT8lg6eodEqN4ohy5bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T14:55:15Z"
    mac: ENC[AES256_GCM,data:M7VfoOr80cIYuIZiM+SSGXeNxsiCfpixOHLntlOMRcC1OPmGqmvQbdQNniUhsw9go/ij+GFYJhscIYGHKHTVmbDR5Yi9fvwFjl/weY0FdcPeEKG7aPW1fE6Ey7HTZQXwvuUNMlB1yUBWs6CMVqycSu61xkxhvVmqlXa6m4GI4Sc=,iv:yct2P4PLbZWHOZjtfBK75UgWQjq6+TNfc+pfwZW+mEI=,tag:foQXKiq0cljg4PK3uQwnyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    version: 3.9.1
