cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
ingressController:
  default: true
  enabled: true
  loadbalancerMode: shared
operator:
  replicas: 2
  rollOutPods: true
rollOutCiliumPods: true
k8sClientRateLimit:
  qps: 50
  burst: 200
l2announcements:
  enabled: true
ipam:
  mode: kubernetes
gatewayAPI:
  enabled: true
socketLB:
  hostNamespaceOnly: true
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true
hubble:
  ui:
    enabled: true
  relay:
    enabled: true
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    # - SYS_MODULE # unsupported in Talos https://docs.cilium.io/en/stable/installation/k8s-install-helm/
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE