apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/o-be-one/kubernetes-at-home.git
      revision: HEAD
      directories:
      - path: 'apps/**'
      - path: 'argocd'
      - path: 'shared-resources/*'
      - path: 'infra/cilium'
  # - pullRequest:
  #     github:
  #       # The GitHub organization or user.
  #       owner: o-be-one
  #       # The Github repository
  #       repo: kubernetes-at-home
  #       # Reference to a Secret containing an access token. (optional)
  #       # tokenRef:
  #       #   secretName: github-token
  #       #   key: token
  #       # (optional) use a GitHub App to access the API instead of a PAT.
  #       # appSecretName: github-repo-creds
  #       # Labels is used to filter the PRs that you want to target. (optional)
  #       labels:
  #       - preview
  #     requeueAfterSeconds: 1800
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      # annotations:
      #   debug-info: '{{ toJson . }}' # help to see all available data, useful to debug and get also possible variables
    spec:
      project: "menia"
      source:
        repoURL: https://github.com/o-be-one/kubernetes-at-home.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: o-be-one
        # The Github repository
        repo: kubernetes-at-home
        # Reference to a Secret containing an access token. (optional)
        # tokenRef:
        #   secretName: github-token
        #   key: token
        # (optional) use a GitHub App to access the API instead of a PAT.
        # appSecretName: github-repo-creds
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - preview
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'pr-{{.branch_slug}}-{{.number}}'
      annotations:
        debug-info: '{{ toJson . }}' # help to see all available data, useful to debug and get also possible variables
    spec:
      project: "menia"
      source:
        repoURL: https://github.com/o-be-one/kubernetes-at-home.git
        targetRevision: '{{.head_sha}}'
        path: apps/
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pr-{{.branch_slug}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true