apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
- httproutes.yaml
- applicationset.yaml

configMapGenerator:
- name: argocd-cm
  literals:
  - kustomize.buildOptions=--enable-alpha-plugins --enable-exec
  behavior: merge
- name: argocd-cmd-params-cm
  literals:
  - server.insecure=true
  behavior: merge

patches:
- path: ksops.yaml

# generators: # works only when ArgoCD is deployed
#   - secret-generator.yaml