apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: netdata-https
spec:
  hostnames:
  - netdata.menia.cc
  parentRefs:
  - name: shared-gateway
    namespace: default
    sectionName: shared-https
  rules:
  - backendRefs:
    - name: netdata
      port: 19999