apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn

resources:
  - namespace.yaml
  - storageclass.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.7.0
    releaseName: longhorn
    namespace: longhorn-system
    includeCRDs: true
    valuesInline:
      persistence:
        defaultClass: true
      defaultSettings:
        defaultReplicaCount: 2
        defaultDataPath: /var/lib/longhorn
        backupTargetCredentialSecret: backup-storage

generators:
  - secret-generator.yaml