apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - backup-storage.enc.yaml