apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: syno-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:2025.10.2
          env:
            - name: TZ
              value: "America/Montreal"
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: homeassistant-data
              mountPath: /config
            - name: homeassistant-config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
      hostNetwork: true
      volumes:
        - name: homeassistant-data
          persistentVolumeClaim:
            claimName: homeassistant-pvc
        - name: homeassistant-config
          configMap:
            name: homeassistant-config
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
