apiVersion: v1
kind: Secret
metadata:
    name: dontstarve-cluster-master
type: Opaque
stringData:
    cluster.ini: ENC[AES256_GCM,data:M6WdohZLJjpoS1TrK81LuMzU+S7N0sjnGp4nvBL2oFc6uKLW1aMpglhewy3LaKDbqvNS6w7/6fiDqak6FeVpTrSrgy5g44U4Lh1BFddLGZazxqAWZ7PBmojyZtpgx256N867/CV1P85c6EAWc289Z83vK8YspnhByZ/JO7s/J9Lvq3Fi8mcuY6MSgdjXZOPWHOYwgLmB7rcs5PEJlwlvGxNQlHHc22s0ywahcFIfR2n7p6ihghpfYpVxXzh5xA14FL9ouu0JgGGwF78zvbbwWYunj++HLlROS3BHDY3zCjZ/JbKgQ7W5e0S7tHqhmubvEBZ2Tfak9CHEc29lbu+0HOtK8XfE8PA7htWVkj7dGi1NuGkk4IjU4/M6sdyXxsOAWIz6FIKBaPS8uTx1rzsDNUMUaePnzvuKOCwNQtZu0BWaCMI85Ai5ahPsWWtFR8OWTUh4MDXpa7WwpK8sH+g+MHefkP7tLWWBvJSlygGD+NFBboPc6ptpYiCqsBNsX56xpqtoKcx6n7DdwesxJBvm5P9ANJtAH9ygkOZ7xhd4Mc25LonB6dFcAvGJLWO6hNKu92Qtih8luz8fw/7UYwfknma9y+TiiiJY5T7Wf1fGBp7w+ROQWqb8FiVj3MsUHNtf6WinS++2hiLJGs0TdpIBB1JsfSwCJmmwb6iiLaQ6dZeBLsT9a6rMCQ==,iv:rnOkThfZz6x7qSMPZluSbLiN4I0FDWVPdMQzgyVpPiY=,tag:cg5w7H7S5ke8/lQe0dCAJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM2R4L2dXYXhmQjltT1VF
            am9ocEcvNnBvUUEvNFAxRFFGWHJCaklHb1ZzCng0WWFRM09JaHBVYWFIRVR1aDNl
            b1MzTGlGWEE5VU1yQ080T1Z1SlloRncKLS0tIGRIWUNWclJnRjFDa05GWTJzbG1C
            YlhPdUdHRnoxenpxWTJwR0s0c1RQZG8Ks1BLN+20Qb8Bwp/jQwQojAcGVsGiZZTc
            X7d6VTRfUs2ETDJMFORNGX4kOQC2H9q0W5Rv9uX8v3qO3tfKpRqJHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZDBOSy9ycDNrZnpPTFFV
            M3Rhek1SUzVrNUhjRzZLb3EyMzVERHM5ZVhRCm5LaWpTREhOWjhRQU0rd3U5bmlV
            YTMxclpNQ01VZkxsZkZkQTFiZUltOHMKLS0tIFFDLythZG9pR2dIUFp5T0RmeFBO
            VHp1WDcyci9lMld4Szh3a3puOTZUSTAKoG5Y1AWyclxi1M3tgMFpPAAf+9kW6QCX
            enatsjrX1y2Wndnwn80izppW2s+KE+sLJLyr2fUQj+19BPwvk+hMZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-06-28T20:35:03Z"
    mac: ENC[AES256_GCM,data:wUuNa/LTF8f0t4UAoq6A9LmpZS5Fi316928HVeV85h60sgIOe97zw1RibIAYRPayYDOcp8a/uiQxVkPsbnHZZ6DRQ0yas4hr3NSSi7X63/e7oYG1uYVSnSMkk50U2C1dZFWjl9v0S5iR6cxXirRd3YgDRl3OZbv80RG7RpKKKw4=,iv:eB3607XW1uI5OimLvibp5QJVEnTett11a/sXsc3bFDo=,tag:trX2/T6/6xhN/5ld5d8CLQ==,type:str]
    version: 3.13.1
