# ************************************************************************** #
#                                                                            #
#     Don't Starve Together - server.ini                                     #
#     Version 210221                                                         #
#     /data/.klei/DoNotStarveTogether/Cluster_1/Master/server.ini            #
#                                                                            #
# ************************************************************************** #
# https://forums.kleientertainment.com/forums/topic/64552-dedicated-server-settings-guide/

[NETWORK]
server_port = 11000

[SHARD]
is_master = true
name = Master

[STEAM]
authentication_port = 8766
master_server_port = 27016