apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance

resources:
  - glance.yaml
  - httproutes.yaml
  - funnel.yaml

configMapGenerator:
  - name: glance-config
    files:
      - configs/glance.yml