apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/o-be-one/kubernetes-at-home.git
      revision: HEAD
      directories:
      - path: 'apps/**'
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: "menia"
      source:
        repoURL: https://github.com/o-be-one/kubernetes-at-home.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: o-be-one
        repo: kubernetes-at-home
        labels:
        - preview
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'pr-{{.branch_slug}}-{{.number}}'
      annotations:
        debug-info: '{{ toJson . }}'
    spec:
      project: "menia"
      source:
        repoURL: https://github.com/o-be-one/kubernetes-at-home.git
        targetRevision: '{{.head_sha}}'
        path: apps/
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pr-{{.branch_slug}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true