apiVersion: v1
kind: Secret
metadata:
    name: dontstarve-cluster-caves
type: Opaque
stringData:
    cluster.ini: ENC[AES256_GCM,data:l7fzvpESwEE/Mtxv+SxrJTU7OpwG4FzZDK1hMOxYyOAf1//JON8LFsU0co3UPheQIF34WzegWQWU0hgO/xPpdi/I4AjjKA/3uby4Z9t2zoRZvfWjlcE4qVgsT+fAPxzSsw02WacCB9tbG6GZ9csNV8ml3kh/zVhThe3FuwVtMdlZ56XsP06NDBNBx7LIBBJ4O786D0ZP7mI8UYAO3XZ5itORnef6IRThUmpULKMpY3MRjYp3reJ6YbTOKRyTPisqvZRcIw54c/LFTt28cOH1ey+526VCp0sH8c8bYZevmuM+c2JovTKCcgHQbiEptcM7HznV/cN8YAIosMTx6YfnQo4y7nchI2Rih8cyexSZ/l9u4RCjzPsfk2uwtM6rG+lNp9gydmM=,iv:j22c6jdK2ZqZOzE0O+/frnDbYnzsm8MYEuQbI2HrrxE=,tag:fxGvLJvYLDu3k9fs6unl/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcXpQQXBXWnEySTczV05H
            cHpkVUJNMFh2RmRFMHZVcGF5VnVOMEFxbkU4CnZKNUIvVzFVV25oS3RQTXpkNHBH
            Wll1WDN2K3JYN0trV1JGOWYzT0ptNzAKLS0tIDd3ZG5BY1p3WHM0Y0VMS2wxNnZS
            d1ZvNktqU0ZpWFQvdkxKbEd0YlJXakUK7EOm+BCO2Ac+C+C44QWQxve1yfQZeyKv
            yHqGMaocgrGPsZTgZqK9dMxsiU7rhABROiSm3EuMgir2DeOtYI59nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RWJpeW05amFCd0J3blNo
            Y2tKWXNBSmEvcnpDTjBXWEdTVVErM01Sa1JVClVUWXJ4QXZjMnpjdlpjdTFIeUlN
            bmplYlZkcllrN25qMVg4R3lhaExQMUEKLS0tIGtIdjVhRkZaSlVBYngxQWRablJj
            TmFraXlWMTAzanpzdDlRVDJXajRURWcK+AuldQwtRiNmiWhKx/wDXV3IIsrsqiHR
            LUmSaOTkoy5woX9Y5Jmbv7tzaG6RBeHkYJV4n7mP1HRslmU4yrZS+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-06-28T20:35:11Z"
    mac: ENC[AES256_GCM,data:Go//a+8aS95nYtvnnwv+Bpm7zfkpZ+iU8OzD7JITje04Sd0OslE/P3UuZbxwbEYAaCqZoAfxRGgsG1jzix+XORTV/0Sy6XrvLQwdVoYP+9DIH6Nb7wBcCUu8VRIsouuCTVHEJCk8xhVKX1jbk3D1BT42yVKsa7w/5+gtPBRHFB8=,iv:X4YdywKYmIR8yF/r2g3lAzercuwIQ3IUczgCrBLKN6I=,tag:oQ0PyoOJc2QJEu4vAG5KyA==,type:str]
    version: 3.13.1
