apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dontstarve

resources:
  - namespace.yaml
  - dontstarve.yaml

configMapGenerator:
  - name: dontstarve-master-config
    files:
      - configs/Master/server.ini
      - configs/Master/dstserver.cfg
  - name: dontstarve-caves-config
    files:
      - configs/Caves/server.ini
      - configs/Caves/dstserver.cfg

generators:
  - secret-generator.yaml
