apiVersion: v1
data:
    SECRET_KEY: ENC[AES256_GCM,data:xcaacvB4cfa0O3+pcAlvawvhYc8R3NyKSrEgEhS4j4Hdwizf3V/Tt1qDjamxgo5OYwzokzWZfQzCgnGDtLcGQvKU9NZZiJl1U3DPGTYQW5OmuGNtkX3qqg==,iv:upMoDeeex6f6+mMcDIPIwrmSvYbQj5kbSOU47E/8iHs=,tag:L4A7ZZCj+IDQQmLp6SpeJQ==,type:str]
kind: Secret
metadata:
    name: playit-client
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RVZMOWowNTk4WUJralNE
            MEo0WWc2Uyt5cytUUUVFRlJqVWxUS0RtN2owCjRhUkFKWU5Wbnl1TTJMZlhNVU1y
            TFBMZWErNVVXNFY4Ly9XZzc1TnlvencKLS0tIHJKVHoxMGFiQnhaMFNSZVo2TllZ
            aE9lMkRIbUs3UVR0UFhDNFRIR0E2blkKsRXqZMhxeXu/wqOE2xMYbFv3JEX1RWvM
            1PfHeR/vYCYvKF8ncodgLosPapbVce4AD3oci56D1VsCyZzBwfbN7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N2VHNnByLytLQStOSnds
            bG0reU5Id29qNE1SWTRydnJrUHB0YU5NUFZRCjh2YnFtakFjM1RnV2NtWnErd0l4
            NjFuYTl6d2dJMWlrVjdISVVqT0dmbWsKLS0tIFQ3bGwxNksrd0lvbWU5MnkvcjY0
            Y3F0VTNpOTQ3SFRVNTVYK0NmRVFFQk0KYqKiJPojExcl9pE3EPYnNYeFUUrzsVOi
            kRZ2bjLeaXnv6Q+2A0JFdg5ea9QkvjSqKCBUdsW6uMiyxlgzwQBHBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-06-28T20:33:27Z"
    mac: ENC[AES256_GCM,data:bfB8lCghFAuqfpo0xQ+lnrf4tudStVs9SbnsQP9+2TV3RTgu8W0Y8yZ91oe8pkY4HM3B6qfReXijqfO95c+FxBY6ZFFiSbcT2enpGFuMA4ns4s3dn0ypac2StLB2Hqd2FmcrNcSciWVVUQJM5AkqlLnJaZ+J9TRuJ1AlkXD6WuU=,iv:bP945B9ieervcY5MRWa2em7FRKeJgdYrFKVBpN/CZVc=,tag:uhQ6pT2hsv9AC5rb0q55QQ==,type:str]
    version: 3.13.1
