pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: reddit
            subreddit: geforcenow

          - type: twitch-channels
            channels:
              - Nidouille77
              - euuhhh__
              - JeanBaptisteShow
              - AdrienLinuxtricks
              - BastiUi
              - Hardisk

      - size: full
        widgets:
          - type: search
            search-engine: duckduckgo
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}
              - title: Kagi
                shortcut: "!k"
                url: https://kagi.com/search?q={QUERY}

          - type: videos
            channels:
              - UCVRJ6D343dX-x730MRP8tNw # cocadmin
              - UCA6rJQnIFgQOcjO-xtNV7lg # Hardisk
              - UC18RieOQuuvjWcHADpZqOFQ # Danfield
              - UC6sYueSaa1TwougrKgyuLvQ # Basti Sans MS
              - UCIh7PDUAP226Pa_NtjN9Jqw # Legend
              - UCYcJNtSv9jSCB0tWMb09O_Q # euuhhh
              - UCB9gfNOymNLIm5J8lf4MhtA # SylvainLyve
              - UCNiauGTV7XhkOpUAIXod4xA # Leo Duff
              - UCXuqSBlHAE6Xw-yeJA0Tunw # LinusTechTips
              - UCBJycsmduvYEL83R_U4JriQ # MKBHD
              - UCwN_MU6-sDwOMArIlYIsKXA # JeanBaptisteShow
              - UCwN_MU6-sDwOMArIlYIsKXA # JeanBaptistePlay

          - type: rss
            limit: 15
            collapse-after: 7
            cache: 3h
            feeds:
              - url: https://feeds.macrumors.com/MacRumors-Front
              - url: https://www.teslarati.com/feed/
              - url: https://noted.lol/rss/
              - url: https://www.theverge.com/rss/index.xml
              - url: https://tldr.tech/api/rss/devops
              - url: https://korben.info/feed

      - size: small
        widgets:
          - type: weather
            location: Montreal, Canada

          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: TSLA
                name: Tesla
              - symbol: AMD
                name: AMD
              - symbol: BTC-USD
                name: Bitcoin

  - name: Tech
    columns:
      - size: small
        widgets:

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 3h
            feeds:
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://awesomekling.github.io/feed.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed

          - type: twitch-channels
            channels:
              - theprimeagen
              - cohhcarnage
              - christitustech
              - blurbs
              - asmongold
              - jembawls

      - size: full
        widgets:
          - type: hacker-news

          - type: videos
            channels:
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
              - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

          - type: reddit
            subreddit: selfhosted