apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synology-csi

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/zebernst/synology-csi-talos/refs/heads/main/deploy/kubernetes/v1.20/controller.yml
  - https://raw.githubusercontent.com/zebernst/synology-csi-talos/refs/heads/main/deploy/kubernetes/v1.20/csi-driver.yml
  - https://raw.githubusercontent.com/zebernst/synology-csi-talos/refs/heads/main/deploy/kubernetes/v1.20/node.yml
  - storageclass.yaml

generators:
  - secret-generator.yaml
