apiVersion: v1
kind: Secret
metadata:
    name: dontstarve-cluster-token
data:
    cluster_token.txt: ENC[AES256_GCM,data:Yy6mYsg+yemvoPaqrgvp4W2IWvVrpdE87KAPMk5LOIEUt0ZH3v79NKZXmlE15mKt0WXmV9dzrGQBN78+yirgACoAQ8PglfghqNhVGG4+5yj6KiUq,iv:/SD2n3UCh9febB1xVdyScofytWY1rANse65umKsyzKU=,tag:ky7gBbUudedLYb95mldsPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbE1icFNmOEIwWnJQSUtu
            cUt3b0J0RXFPK3prUm9KenlCTWtPY1dJQWpnCk1qb3BCazlWQmNCbmduTk54TWhn
            SlY4UTdxWWJoWkFrWWppT09Odk56QW8KLS0tIGpaUjJpUkEvT255OG5xZHcrUCtH
            U2ltU3Z0SEZvZzcvM1lkcVd6S2lZQncKZS3aOMXPG24xW7G+c+iLdyLzdnvi/2wm
            5jDrgx4HFAiNmJxtx2vhfxn9PDc2r9ZeRiZFHtZwHu5gXovADirG9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngkdczpldhxhx8qchl0v7c9eq06vnc5yea3mhsuy0n20hvyescpqv3w2xy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQTZ5OXhFWForK3luK1Bx
            TllSZFZJb054VzIydkFuMHlUSVpFQ3M3R0NZCmJVTUVwaHdhOVNVMmxBQjZQK05s
            Y2c4cFdESzFiblF4aVpvNFR0RFBkdGMKLS0tIHovazJhdVVybitZanZwK2NiY285
            U1EwcDA4RFNwdjhBQklTRkRwcFlxUUUK8VIWpWWN/yajWbnNLb4A0o6uob0GePbv
            xeJoyWFg/2GpbMpIKuwMDWiy/fMkfCTj8aJ+1aATW0meoQ0kARtJHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xzxw8fsvdz53aa3r8z6t4zns2cqadjm4ep88w5jf4zw3yhcflvesxgkxlc
    encrypted_regex: ^(data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId)$
    lastmodified: "2026-06-28T20:33:54Z"
    mac: ENC[AES256_GCM,data:xkkB21C7BoowLxNqqGLIF1Q6JRblxsCwniizH2OGFv9XhCxhCz6dMQr0O+Uo//B3yOU1q+PFuE40X0oeSIEWnNf0Lzz+h/V2uglYcscDXSjGzV7/+IBIOozvY32Cx35TdEddfXds5cFDbgMx+FyQWPTrDTTxB5Bg/CEqdHlXt0o=,iv:4qJr5FIdr9vJcg6jG07BL9BYlSq6njEChC3uYMdVs58=,tag:eK+v8ul/4rpLxpvvpyM78g==,type:str]
    version: 3.13.1
